projects:
  tsg:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/graphql/types.d.ts
        docsFilePath: src/graphql
        graphQLApiId: tnkwa2fpwzfrbatycokedz7l54
      endpoints:
        prod: >-
          https://ttoa426gevacffst6v7e5yiwd4.appsync-api.us-east-1.amazonaws.com/graphql
