---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: tsg-ingress
  namespace: prod
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  tls:
    - hosts:
        - "austin.hmm.dev"
      secretName: tsg-secrets
  rules:
    - host: "austin.hmm.dev"
      http:
        paths:
          - path: /
            backend:
              serviceName: tsg-service
              servicePort: 8080
