version: 2.1

jobs:
  build-web:
    working_directory: ~/tsg
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-web-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "web/yarn.lock" }}
            - v1-web-dependencies

      - run:
          name: Installing root dependencies
          command: yarn install

      - run:
          name: Installing web dependencies
          command: yarn --cwd web install

      - run:
          name: Run front end web tests
          command: yarn test:web

      - run:
          name: Build bundle and all assets
          command: REACT_APP_VERSION=${CIRCLE_SHA1} yarn build:web

      - save_cache:
          paths:
            - node_modules
            - web/node_modules
          key: v1-web-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "web/yarn.lock" }}

      - run:
          name: Clean up workspace
          command: rm -rf web/node_modules

      - persist_to_workspace:
          root: ./
          paths:
            - ./

  deploy-web:
    working_directory: ~/tsg
    docker:
      - image: circleci/node:latest
    steps:
      - attach_workspace:
          at: ./

      - run:
          name: Move sourcemaps to their own directory
          command: mkdir sm && mv web/build/static/js/*.map sm/

      - run:
          name: Upload production web bundle to S3 and invalidate CloudFront distribution
          command: yarn deploy:web

      - run:
          name: Deployment notification to Rollbar for tsg-web
          command: |
            curl https://api.rollbar.com/api/1/deploy/ \
              -F access_token=$ROLLBAR_WEB_DEPLOY_TOKEN \
              -F environment=production \
              -F revision=$CIRCLE_SHA1 \
              -F local_username=$CIRCLE_USERNAME

      - run:
          name: Move JS files to the sourcemap directory
          command: mv web/build/static/js/*.js sm/

      - run:
          name: Upload Rollbar sourcemaps
          command: |
            cd sm
            find **.js | while read file
            do
              curl https://api.rollbar.com/api/1/sourcemap/ \
                -F access_token=$ROLLBAR_WEB_DEPLOY_TOKEN \
                -F version=$CIRCLE_SHA1 \
                -F minified_url=https://tsg.hmm.dev/static/js/$file \
                -F source_map=@"${file}.map"
            done

  deploy-api:
    working_directory: ~/tsg
    docker:
      - image: circleci/node:latest
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-api-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "api/yarn.lock" }}
            - v1-api-dependencies

      - run:
          name: Installing API dependencies
          command: yarn --cwd api install

      - run:
          name: Deploying API
          command: yarn --cwd api deploy:prod

      - save_cache:
          paths:
            - node_modules
            - api/node_modules
          key: v1-api-dependencies-{{ checksum "yarn.lock" }}-{{ checksum "api/yarn.lock" }}

workflows:
  version: 2
  tsg:
    jobs:
      - build-web:
          context: maingot

      - deploy-web:
          context: maingot
          requires:
            - build-web
          filters:
            branches:
                only: master

      - deploy-api:
          context: maingot
          requires:
            - deploy-web
          filters:
            branches:
                only: master
