version: 2
jobs:
    build:
        working_directory: ~/tsg-front
        docker:
            - image: circleci/node:9.8.0
        steps:
            - checkout

            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package-lock.json" }}
                    - v1-dependencies

            - run: 
                name: Installing All Packages
                command: npm install

            - run:
                name: TypeScript Linter
                command: mkdir reports && npm run lint:ci

            - run:
                name: Build Bundle for Distribution
                command: npm run build

            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package-lock.json" }}

            - run:
                name: Clean up workspace
                command: rm -rf node_modules
            
            - store_test_results:
                path: reports/
            - store_artifacts:
                path: reports/

            - persist_to_workspace:
                root: ./
                paths:
                    - ./

    deploy-env:
        working_directory: ~/tsg-front
        docker:
            - image: google/cloud-sdk
        steps:
            - checkout
            - attach_workspace:
                at: ./
            - run: 
                name: Decode and Store Service Account
                command: echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
            - run: 
                name: Activate Google Could Service Account
                command: gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            - run: 
                name: Set Google Could Project
                command: gcloud --quiet config set project ${GCLOUD_PROJECT}
            - run:
                name: Copy Bundle to GCP Bucket
                command: gsutil cp dist/** gs://${GCLOUD_BUCKET}/front-assets/${CIRCLE_BRANCH}

    deploy-prod:
        working_directory: ~/tsg-front
        docker:
            - image: google/cloud-sdk
        steps:
            - checkout
            - attach_workspace:
                at: ./
            - run: 
                name: Decode and Store Service Account
                command: echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
            - run: 
                name: Activate Google Could Service Account
                command: gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            - run: 
                name: Set Google Could Project
                command: gcloud --quiet config set project ${GCLOUD_PROJECT}
            - run:
                name: Copy Bundle to GCP Bucket
                command: gsutil cp dist/** gs://${GCLOUD_BUCKET}/front-assets/production

workflows:
    version: 2
    tsg-front:
        jobs:
            - build:
                context: maingot
                filters:
                    branches:
                        only: /.*/
                    tags:
                        only: /.*/

            - deploy-env:
                context: maingot
                requires:
                    - build
                filters:
                    branches:
                        only: /^(?!production).*$/
                    tags:
                        ignore: /.*/

            - deploy-prod:
                context: maingot
                requires:
                    - build
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /^(v\d+)\.\d+.(\d+)$/
