service:
  name: tsg-api
  app: tsg

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  tracing:
    apiGateway: true
    lambda: true
  logs:
    restApi:
      level: INFO
      executionLogging: true
      fullExecutionData: true
    frameworkLambda: true
  individually: true
  memorySize: 128
  role: LambdaRole
  environment:
    AWS_XRAY_CONTEXT_MISSING: LOG_ERROR
    CLIENT_TABLE: ${self:service.app}-ClientTable-${self:provider.stage}
    USER_TABLE: ${self:service.app}-UserTable-${self:provider.stage}
    CUSTOMER_TABLE: ${self:service.app}-CustomerTable-${self:provider.stage}
    JOB_TABLE: ${self:service.app}-JobTable-${self:provider.stage}
    NODE_PATH: "./:/opt/node_modules"
    ENV: ${self:provider.stage}
    CODE_VERSION: ${env:CIRCLE_SHA1}

layers:
  shared:
    path: layer
    name: ${self:service.app}-SharedLayer-${self:provider.stage}
    description: "Additional ${self:service.app} nodejs dependencies"
    compatibleRuntimes:
      - ${self:provider.runtime}

custom:
  serverless-offline:
    port: 3001
  corsConfig: &corsConfig
    origin: "*"
    allowCredentials: true
  authorizerConfig: &authorizerConfig
    type: COGNITO_USER_POOLS
    authorizerId:
      Ref: ApiGatewayAuthorizer

functions:
  signup:
    handler: handlers/signUp.default
    layers:
      - { Ref: SharedLambdaLayer }
    events:
      - http:
          method: post
          path: signup
          cors: *corsConfig
          authorizer: *authorizerConfig

resources:
  Resources:
    UserPool: ${file(./resources/UserPool.yml)}
    UserPoolClient: ${file(./resources/UserPoolClient.yml)}
    ApiGatewayAuthorizer: ${file(./resources/ApiGatewayAuthorizer.yml)}
    GatewayResponseDefault4XX: ${file(./resources/GatewayResponseDefault4XX.yml)}
    ClientTable: ${file(./resources/ClientTable.yml)}
    UserTable: ${file(./resources/UserTable.yml)}
    CustomerTable: ${file(./resources/CustomerTable.yml)}
    JobTable: ${file(./resources/JobTable.yml)}
    LambdaRole: ${file(./resources/LambdaRole.yml)}
